[package]
name = "finalfusion"
version = "0.1.0"
authors = ["DaniÃ«l de Kok <me@danieldk.eu>"]
edition = "2018"

[lib]
name = "finalfusion"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.5"
features = ["extension-module"]

[dependencies]
failure = "0.1"
rust2vec = "0.5.1"
toml = "0.4"
